common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: admin@123

development:
  <<: *common
  database: cowcamo_development

test:
  <<: *common
  database: cowcamo_test

staging:
  <<: *common
  database: cowcamo_staging

production:
  <<: *common
  database: cowcamo